### ISSUE TITLE
Edit misleading comments

### ISSUE THREAD

**Issue by yanntm** [lovasoa/bloomfilter#1]
Just browsing your class, 
https://github.com/lovasoa/bloomfilter/blob/master/src/main/java/BloomFilter.java#L41-L45
This comment is very misleading and seems to be a counter-sense.
It should read : 

* If it returns false, element o it is *not* in the set (guaranteed), 
* Else if it  returns true, the element is *probably* in the set with probability 1-p, where p is your equation with the log.

So, no false negatives, but false positive are possible.

**Comment by lovasoa** [comment]
How is the comment misleading ?

 - If the element is in the set, the function is guaranteed to return true 
 - If the element is not, the function will *probably* return false

How would presenting things in terms of what the function returns instead of whether the element is in the set (which is the property users are supposedly interested in) help ?

Maybe presenting both perspectives would help, though. What would you think about : 

```
  /** 
  * If the element is in the container, returns true.
  * If the element is not in the container, returns true with a probability ≈ e^(-ln(2)² * m/n), otherwise false.
  * So, when m is large enough, the return value can be interpreted as:
  *    - true  : the element is probably in the container
  *    - false : the element is definitely not in the container
  **/
```

**Comment by yanntm** [comment]
Yes I think that would be much more explicit and easier to read. 

I did read it several times to convince myself it was wrong before posting an issue, but given your answer and reading it again, I can see now that the way it was expressed is actually correct. 

I think the idea of reversing it is talking about how much you can trust the return value,  false is trusted, true is not. So I'd rather talk about the probability of true being wrong than talk in the same sentence about false result and a probability.

Thanks for making this code available btw, I might adopt your class into some of my code base to make a Blash table (Bloom in front of a Hash, when false results to contains are common is a good idea).
